apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-management-vs
  namespace: {{ .Values.app.namespace }}
spec:
  hosts:
  - {{ .Values.app.userManagementBackend.host }}
  gateways:
  - user-management-gateway
  http:
  - route:
    - destination:
        host: user-management-svc
        port:
          number: 3000
