app:
  namespace: helmetapp
  eventManagementBackend:
    replicaCount: 2
    image:
      repo: justin89721/event-management-service
      tag: 30d5efac012d64c83af2e57ebd22f77241d5588f
    host: event.tsmc.n0b.me
  userManagementBackend:
    replicaCount: 2
    image:
      repo: justin89721/user-management-service
      tag: 2a92b99320fe50aa78240dd4d93b2d72e706a153
    host: user.tsmc.n0b.me
  frontend:
    replicaCount: 2
    host: ui.tsmc.n0b.me
    image:
      repo: justin89721/meichuhackathon-frontend
      tag: c2675bf9da6cb42b3d335de312d3fb08a899d9fe
