app:
  namespace: helmetapp
  eventManagementBackend:
    replicaCount: 2
    image:
      repo: justin89721/event-management-service
      tag: 677ef5085b191f945c0af105ca2cbbd1a9835022
    host: event.tsmc.n0b.me
  userManagementBackend:
    replicaCount: 2
    image:
      repo: justin89721/user-management-service
      tag: 2a92b99320fe50aa78240dd4d93b2d72e706a153
    host: user.tsmc.n0b.me
  frontend:
    replicaCount: 2
    host: ui.tsmc.n0b.me
