app:
  namespace: helmetapp
  eventManagementBackend:
    replicaCount: 2
    image:
      repo: noball/event-management-service
      tag: latest
    host: event.tsmc.n0b.me
  frontend:
    replicaCount: 2
    host: ui.tsmc.n0b.me