apiVersion: v1
kind: Service
metadata:
  name: event-handler-svc
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: event-handler