apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: event-handler-vs
  namespace: {{ .Values.app.namespace }}
spec:
  hosts:
  - {{ .Values.app.eventHandler.host }}
  gateways:
  - event-handler-gateway
  http:
  - route:
    - destination:
        host: event-handler-svc
        port:
          number: 5280
