apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: frontend