apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-vs
  namespace: {{ .Values.app.namespace }}
spec:
  hosts:
  - {{ .Values.app.frontend.host }}
  gateways:
  - frontend-gateway
  http:
  - route:
    - destination:
        host: frontend-svc
        port:
          number: 8080
