apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alert-chatbot-vs
  namespace: {{ .Values.app.namespace }}
spec:
  hosts:
  - {{ .Values.app.alertBot.host }}
  gateways:
  - alert-chatbot-gateway
  http:
  - route:
    - destination:
        host: alert-chatbot-svc
        port:
          number: 3000
