apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: event-management-vs
  namespace: {{ .Values.app.namespace }}
spec:
  hosts:
  - {{ .Values.app.eventManagementBackend.host }}
  gateways:
  - event-management-gateway
  http:
  - route:
    - destination:
        host: event-management-svc
        port:
          number: 3000
