apiVersion: v1
kind: Service
metadata:
  name: event-management-svc
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: event-management